### ISSUE TITLE
Consider collaborating with Finder

### ISSUE THREAD

**Issue by Atrate** [warren-bank/Android-SMS-Automatic-Reply-GPS#3]
Finder is an Android app that serves the exact same purpose as this app, yet is more developed.

It may be beneficial to put effort into contributing to Finder, instead of developing a separate app with the same premise.

https://github.com/Seva-coder/Finder

**Comment by warren-bank** [comment]
Thanks for telling me about _Finder_. I wasn't aware of that app.
It looks awesome.. much better than this one.

I only wrote this app quickly, as a useful experiment.. while playing around with SMS-related APIs.
It works, but as you suggest.. isn't very polished.

**Comment by warren-bank** [comment]
I'm curious why the minSDK in _Finder_ is [17](https://github.com/Seva-coder/Finder/blob/v2.4/app/build.gradle#L7) (Android 4.2).
This app only requires [11](https://github.com/warren-bank/Android-SMS-Automatic-Reply-GPS/blob/v2.1.7/android-studio-project/constants.gradle#L5) (Android 3.0).

**Comment by Atrate** [comment]
This could be a good trope to follow — if it doesn't require too many hacky workarounds, making Finder more compatible with older Android versions could prove very useful
