### ISSUE TITLE
How to install this app on an Android phone? 

### ISSUE THREAD

**Issue by jorisvergeest** [warren-bank/Android-SMS-Automatic-Reply-GPS#4]
Sorry, this seems the only way to ask this question: how to install this app on an Android phone?
Is it just a matter of copying the APK file, and install from there? Thank you, Joris

**Comment by warren-bank** [comment]
* [google search of topic](https://www.google.com/search?q=how+to+sideload+android+apk)
* [top result](https://www.howtogeek.com/313433/how-to-sideload-apps-on-android/)
  - walks you through the steps in excruciating detail
